### ISSUE TITLE
It's not working properly. How do I install it on Windows 11, and how can I remove GROQ or OpenAI?

### ISSUE THREAD

**Issue by GardenMalcom** [SamurAIGPT/Text-To-Video-AI#17]
It's not working properly. How do I install it on Windows 11, and how can I remove GROQ or OpenAI?

**Comment by GardenMalcom** [comment]
It's not working on Colab, even after providing the API key. : Traceback (most recent call last):
  File "/content/Text-To-Video-AI/app.py", line 7, in <module>
    from utility.script.script_generator import generate_script
  File "/content/Text-To-Video-AI/utility/script/script_generator.py", line 14, in <module>
    client = OpenAI(api_key=OPENAI_API_KEY)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_client.py", line 104, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

**Comment by Anil-matcha** [comment]
Have you setup the environment variable properly
